### ISSUE TITLE
Pausing the game makes Duration longer and incorrect

### ISSUE THREAD

**Issue by 5long** [false-spring/gbfr-logs#106]
In an offline game where I play with AI teammates, pausing the game will not pause the Duration since it tracks wall clock. Because of the inflated Duration, DPS calculation is lower than expected since no player can deal damage while the game is paused.

Example: in this AFK farming game: [189_damage_log.csv](https://github.com/false-spring/gbfr-logs/files/14892766/189_damage_log.csv) I paused the game when the first time my AI teammates deal damage. About 2 minutes later I resumed the game and finished it without more pauses. The game ends with IGT=02:47 but Duration=05:54.

Sometimes I have to pause the game to go to use the bathroom and my DPS would go down the drain together. Hopefully the parser can work around this situation

**Comment by false-spring** [comment]
This is sort of expected behaviour for now. We could maybe add in more work for offline mode pause tracking, but it gets pretty tricky to support currently..

DPS is calculated as the total damage, divided across the duration of real-world time between "first damage instance" and "last damage instance", which makes it pretty simple to calculate. These damage instance timestamps aren't game-time based, but real-time timestamps.

Unfortunately, this causes issues when the game is paused when you are in offline-mode, compared to online-mode where the game still continues even while paused.

Going to close for now.. but will keep this in mind to see how we could solve this in the future 👍
